---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
    config:
      config: client/.eslintrc
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-48

ratings:
  paths:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - "**.erb"
  - "**.rb"
  - "**.css"
  - "**.js"
  - "**.jsx"

exclude_paths:
- client/coverage/
- client/node_modules/
- config/
- coverage/
- db/
- node_modules/
- public/webpack
- spec/
- vendor/
