AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'client/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'
