language: ruby
rvm:
  - 2.3.4

env:
  - TRAVIS_NODE_VERSION="4"

install:
addons:
  postgresql: "9.4"

install:
  - bundle install
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
  - npm install -g yarn

before_script:
  - psql -c 'create database the_great_war_test;' -U postgres

script:
  - npm test
  - bundle exec rspec