dist: trusty
sudo: false

language: ruby
rvm:
  - 2.3.4

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
  region: us-west-2
  app: the_great_war
  env: staging
  bucket_name: elasticbeanstalk-us-west-2-759440491579
  on:
    all_branches: true
    repo: jgramoll/the_great_war
