dist: trusty
sudo: false

language: ruby
rvm:
  - 2.3.4

cache:
  directories:
    - client/node_modules

env:
  global:
    - TRAVIS_NODE_VERSION="6.7"

addons:
  - postgresql: "9.4"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - bundle install
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g yarn
  - npm install

before_script:
  - psql -c 'create database the_great_war_test;' -U postgres

script:
  - bundle exec rspec
  - cd client && yarn install && karma start --single-run && cd ..
