dist: trusty
sudo: false

language: ruby
rvm:
  - 2.3.4

cache:
  directories:
    - client/node_modules

env:
  global:
    - TRAVIS_NODE_VERSION="6.7"

addons:
  - postgresql: "9.4"
  - chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost

install:
  - bundle install
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g yarn
  - npm install

before_script:
  - psql -c 'create database the_great_war_test;' -U postgres

script:
  - bundle exec rspec
  - cd client && karma start --single-run && cd ..
