dist: trusty
sudo: false

language: ruby
rvm:
  - 2.3.4

install:
  - echo install

script:
  - echo script
  - echo $test

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
  region: us-west-2
  app: the_great_war
  env: staging
  bucket_name: elasticbeanstalk-us-west-2-759440491579
  only_create_app_version: "true"
  on:
    all_branches: true
    repo: jgramoll/the_great_war
