export const SUBMIT_GAME_SUCCESS = 'SUBMIT_COMMENT_SUCCESS'
export const SUBMIT_GAME_FAILURE = 'SUBMIT_COMMENT_FAILURE'

export const SET_IS_SAVING = 'SET_IS_SAVING'
export const SELECT_GAME = 'SELECT_GAME'
